In [2]:
import numpy as np

x = np.array([1,2,3])
print(x.__class__)
print('\n')
print(x.shape)
print('\n')
print(x.ndim)

<class 'numpy.ndarray'>


(3,)


1


In [3]:
W = np.array([[1,2,3], [4,5,6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


In [5]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])

print(W + X)
print('\n')
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]


[[ 0  2  6]
 [12 20 30]]


In [6]:
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [7]:
A = np.array([[1,2], [3,4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

np.int64(32)

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [11]:
import numpy as np

W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10,2)
h = np.matmul(x, W1) + b1

print(W1)
print('\n')
print(b1)
print('\n')
print(x)
print('\n')
print(h)

[[ 0.28840991  0.78654955  1.05401662  1.02072411]
 [ 0.83453601 -0.33770056 -0.0077666  -0.02173054]]


[-0.11588849  0.87964667 -0.46705973  0.44729903]


[[-0.35043262  0.98259146]
 [-0.31489667  0.25316626]
 [-0.50575812  2.86053685]
 [ 0.0148909  -1.52154681]
 [-1.45023686 -0.37390005]
 [ 0.52858519  1.3547407 ]
 [ 1.10042386 -0.06085804]
 [-0.09787966 -0.72373574]
 [-1.08721688  0.72536522]
 [-1.39736391 -0.61746612]]


[[ 0.60305123  0.27219236 -0.84405294  0.06825176]
 [ 0.00456855  0.54647045 -0.8009323   0.12037496]
 [ 2.12546687 -0.48416206 -1.02235385 -0.13110148]
 [-1.3813794   1.40518632 -0.43954723  0.49556256]
 [-0.84618422 -0.13477023 -1.99272955 -1.02486766]
 [ 1.16714061  0.83790842  0.0795561   0.95739943]
 [ 0.15069643  1.76573636  0.69327796  1.57185068]
 [-0.74810149  1.04706543 -0.56460556  0.36311807]
 [ 0.17589079 -0.22045952 -1.61863802 -0.67821204]
 [-1.0341998  -0.01093062 -1.9351089  -0.96560613]]


In [12]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1 #hidden layer
a = sigmoid(h) # activation function
s = np.matmul(a, W2) + b2 #score

In [13]:
a.shape

(10, 4)

In [14]:
s

array([[ 2.712038  ,  1.233576  , -0.60115903],
       [ 2.71709108,  1.48184842, -1.55572546],
       [ 2.89363319,  0.90125419, -0.95304901],
       [ 2.72626671,  1.31825802, -0.57174749],
       [ 2.68773888,  1.12457925, -1.10987361],
       [ 2.63190017,  0.98809885, -1.46132103],
       [ 2.88966708,  0.84091914, -1.0890711 ],
       [ 2.71663469,  1.26318188, -0.05493915],
       [ 2.76078504,  1.04460489, -0.77133852],
       [ 2.99857979,  0.841237  , -0.83519667]])

## 순전파 구현

In [15]:
import numpy as np

class Sigmoid:
    def __init__(self): # 생성자(constructor) : 클래스의 인스턴스 생성(객체 만들 때) 자동으로 호출되어 객체의 초기 상태를 설정
        self.params = []
    
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b 
        return out


In [18]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


In [21]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)
s.shape

(10, 3)