In [1]:
import numpy as np

x = np.array([1,2,3])
print(x.__class__)
print('\n')
print(x.shape)
print('\n')
print(x.ndim)

<class 'numpy.ndarray'>


(3,)


1


In [2]:
W = np.array([[1,2,3], [4,5,6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


In [3]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])

print(W + X)
print('\n')
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]


[[ 0  2  6]
 [12 20 30]]


In [4]:
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [5]:
A = np.array([[1,2], [3,4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

np.int64(32)

In [7]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [8]:
import numpy as np

W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10,2)
h = np.matmul(x, W1) + b1

print(W1)
print('\n')
print(b1)
print('\n')
print(x)
print('\n')
print(h)

[[-0.49542708 -0.7948357  -0.14253663  0.06837363]
 [-0.39235115  0.68622283 -0.50397441  0.10592286]]


[ 1.61595218 -0.82782487 -0.85693703  0.76439157]


[[-2.6824547  -0.98799699]
 [ 0.57158236  0.96449724]
 [ 1.86328169  0.23927408]
 [ 1.44991002  0.20196825]
 [ 0.56557973 -2.1559205 ]
 [-0.34816641 -0.18705732]
 [ 1.11389209  0.31056282]
 [ 0.83378764 -1.45609444]
 [ 1.36392299 -0.22703606]
 [-2.25286999 -0.34617285]]


[[ 3.33255464  0.62629981  0.02333624  0.47633094]
 [ 0.9543532  -0.62027891 -1.42449039  0.90563503]
 [ 0.59895251 -2.14463234 -1.24311095  0.91713549]
 [ 0.81838502 -1.8416699  -1.16538916  0.88492023]
 [ 2.18162655 -2.75680969  0.14897591  0.57470105]
 [ 1.8618354  -0.67945277 -0.71303846  0.72077252]
 [ 0.9422502  -1.50007077 -1.17222318  0.87344811]
 [ 1.77417153 -2.4897543  -0.24194797  0.66716697]
 [ 1.02930565 -2.06771689 -0.93692566  0.83359963]
 [ 2.8679063   0.72528493 -0.36135826  0.57368706]]


In [9]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1 #hidden layer
a = sigmoid(h) # activation function
s = np.matmul(a, W2) + b2 #score

In [10]:
a.shape

(10, 4)

In [11]:
s

array([[-2.45479651,  3.37861666, -0.2260977 ],
       [-2.88777826,  3.86867618, -0.23574936],
       [-2.65487226,  4.07427302, -0.30358031],
       [-2.56952383,  3.27138183,  0.05241078],
       [-2.497844  ,  3.43739228, -0.18711382],
       [-2.16508413,  2.87079084, -0.20110258],
       [-2.43259768,  4.04616065, -0.3278081 ],
       [-2.16101503,  2.70499242, -0.09617816],
       [-2.19519297,  2.447645  ,  0.0800892 ],
       [-2.55325641,  3.70978741, -0.04889342]])

## 순전파 구현

In [12]:
import numpy as np

class Sigmoid:
    def __init__(self): # 생성자(constructor) : 클래스의 인스턴스 생성(객체 만들 때) 자동으로 호출되어 객체의 초기 상태를 설정
        self.params = []
    
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b 
        return out


In [13]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


In [14]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)
s.shape

(10, 3)

In [15]:
import numpy as np

D, N = 8, 7

x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0) # 순전파
dy = np.random.randn(N,D) # 무작위 기울기
dx = np.sum(dy, axis=0, keepdims=True) # 역전파


In [16]:
D, N = 8, 7
x = np.random.randn(N, D) # 입력
y = np.sum(x, axis=0, keepdims=True) # 순전파

dy = np.random.randn(1, D) # 무작위 기울기
dx = np.repeat(dy, N, axis=0) # 역전파 


In [17]:
class MatMul:
    def __init__(self, W):
        self.params = [W] # W(가중치 행렬)을 리스트로 저장
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.matmul(x, W)
        self.x = x
        return out
    
    def backward(self, dout):
        W, = self.params
        dx = np.matmul(dout, W.T)
        dW = np.matmul(self.x.T, dout)
        self.grads[0][...] = dW #[...] : 생략 기호 => 넘파이 배열이 가리키는 메모리 위치를 고정시킨 다음 그 위치에 원소 덮어쓰기
        return dx

In [18]:
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None
    
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out # sigmoid의 미분 결과
        return dx

In [19]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None
    
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        self.x = x
        return out
    
    def backward(self, dout):
        W, b = self.params
        dx = np.matmul(dout, W.T)
        dW = np.matmul(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx


## 확률적 경사 하강법(SGD)

In [20]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr # 학습률

    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]